#!/usr/bin/env python3
import sys
import os

DNS_SERVERS = {
    "shecan": ["178.22.122.100", "185.51.200.2"],
    "electro": ["78.157.42.100", "78.157.42.101"],
    "radar": ["10.202.10.10", "10.202.10.11"],
    "google": ["8.8.8.8", "8.8.4.4"],
    "cloudflare": ["1.1.1.1", "1.0.0.1"],
    "clear": []
}

def set_dns(dns_list):
    if not os.geteuid() == 0:
        print("❌ Error: Please run as root (sudo)")
        sys.exit(1)
        
    try:
        with open("/etc/resolv.conf", "w") as f:
            f.write("# Generated by Auto-DNS-Switcher\n")
            for ip in dns_list:
                f.write(f"nameserver {ip}\n")
            if not dns_list:
                f.write("nameserver 8.8.8.8\nnameserver 1.1.1.1\n")
        print("✅ DNS successfully updated!")
    except Exception as e:
        print(f"❌ Failed to set DNS: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in DNS_SERVERS:
        print("Auto-DNS-Switcher by HafezMosleh")
        print("Usage: python3 dns.py [shecan|electro|radar|google|cloudflare|clear]")
        sys.exit(0)
    
    choice = sys.argv[1]
    print(f"🔄 Switching DNS to {choice.upper()}...")
    set_dns(DNS_SERVERS[choice])
